workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 21

    scripts:
      - name: Get dependencies
        script: |
          chmod +x gradlew
          ./gradlew dependencies

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/reports/**

    publishing:
      email:
        recipients:
          - your-email@example.com
